// Code generated by senseBox Blockly on Mon Dec 09 2024 15:38:04 GMT+0100
// (Mitteleuropäische Normalzeit)

#include <SolarChargerSB041.h>;
#include <senseBoxIO.h>

SolarChargerSB041 charger;

void setup() {
  SerialUSB.begin(9600);
  charger.begin();
}

void loop() {
  charger.update();
  SerialUSB.println(charger.isChargerConnected());
  SerialUSB.println(charger.getSolarPanelVoltage());
  SerialUSB.println(charger.getBatteryVoltage());
  SerialUSB.println(charger.isCharging());
  SerialUSB.println(charger.isFastCharging());
  SerialUSB.println(charger.getBatteryLevel());
  SerialUSB.println(charger.isGoodInputVoltage());
  SerialUSB.println(charger.isBatteryPresent());
  SerialUSB.println(charger.getBatteryTemperature());
  delay(1000);
}